# Generated by Django 5.1.2 on 2024-11-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('course', models.TextField()),
            ],
        ),
    ]
